openapi: 3.0.3
info:
  title: Visual Revival API
  description: Visual Revival API Documention for AWS and Wordpress
  version: 1.1.0
  contact:
    email: austin@blythe.io
tags:
  - name: Wordpress
    description: Wordpress Endpoints
  - name: AWS
    description: AWS Endpoints
  - name: Pack Processor Output
    description: |
      Schema for JSON file sent from Pack Processor to AWS
      <SchemaDefinition schemaRef="#/components/schemas/PackProcessorOutput" />
paths:
  /bundle:
    put:
      tags:
        - Wordpress
      summary: Update bundle media
      description: Update an existing bundle's media assets
      operationId: updateBundleMedia
      requestBody:
        $ref: "#/components/requestBodies/UpdateBundle"
      responses:
        "204":
          description: Bundle updated
        "400":
          description: Invalid request
        "404":
          description: Bundle not found
  /product:
    post:
      tags:
        - Wordpress
      summary: Create product
      description: Create a new product
      operationId: createProduct
      requestBody:
        $ref: "#/components/requestBodies/CreateProduct"
      responses:
        "201":
          description: Product created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductResponse"
        "400":
          description: Invalid request
    put:
      tags:
        - Wordpress
      summary: Update product media
      description: Update an existing product's media assets
      operationId: updateProductMedia
      requestBody:
        $ref: "#/components/requestBodies/UpdateProduct"
      responses:
        "204":
          description: Product updated
        "400":
          description: Invalid request
        "404":
          description: Product not found
  /download/{downloadId}:
    servers:
      - url: https://obev9z9046.execute-api.us-west-2.amazonaws.com
        description: AWS dev stage
    get:
      tags:
        - AWS
      summary: Get download by ID
      description: Gets a single download by ID
      operationId: getDownloadById
      parameters:
        - name: downloadId
          in: path
          description: The ID of the download
          required: true
          schema:
            type: string
            format: uuid
        - name: filename
          in: query
          description: The filename the browser should use when saving the file to the user's filesystem. If not provided, the last saved filename from AWS will be used.
          required: false
          schema:
            type: string
            example: Filename123.mp4
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DownloadResponse"
        "400":
          description: Invalid request
        "404":
          description: Download not found
servers:
  - url: https://visualrevival.wordpress.com/api/v1
components:
  requestBodies:
    UpdateBundle:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/UpdateBundle"
      description: Bundle object to be updated
      required: true
    UpdateProduct:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/UpdateProduct"
      description: Product object to be updated
      required: true
    CreateProduct:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CreateProduct"
      description: Product object to be created
      required: true
  schemas:
    ProductResponse:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
          example: 5
          description: Unique product ID generated by Wordpress
    DownloadResponse:
      type: object
      required:
        - id
        - url
      properties:
        id:
          type: string
          format: uuid
          description: Unique download ID generated in AWS
        url:
          type: string
          example: https://cloudfront.net/productid/downloadid.mp4?Expires=1234&Signature=ABCD
          description: Full download URL with CloudFront signing parameters
    NewDownload:
      type: object
      required:
        - filename
        - type
        - format
        - url
        - size
      properties:
        filename:
          type: string
          example: Filename.mp4
          description: Friendly name of file including extension
        type:
          type: string
          description: Content type
          enum:
            - motion-background
            - still
            - countdown
            - motion-title
            - title-slide
            - title-overlay
            - propresenter-7
        format:
          type: string
          description: File format
          enum:
            - mp4
            - zip
            - jpeg
            - prores
            - png
        resolution:
          type: string
          description: Friendly name for resolution
          enum:
            - 6k-pro
            - 4K-pro
            - 1080p-pro
            - 4K
            - 1080p
            - 720p
            - dw-pro
            - tw-pro
        url:
          type: string
          example: https://cloudfront.net/productid/downloadid.mp4
          description: Base URL for download without signing parameters
        size:
          type: integer
          format: int64
          description: File size in bytes
          example: 24523
    Download:
      type: object
      required:
        - filename
        - type
        - format
        - url
        - size
      properties:
        id:
          type: string
          format: uuid
          description: Unique download ID generated in AWS
        filename:
          type: string
          example: Filename.mp4
          description: Friendly name of file including extension
        type:
          type: string
          description: Content type
          enum:
            - motion-background
            - still
            - countdown
            - motion-title
            - title-slide
            - title-overlay
            - propresenter-7
        format:
          type: string
          description: File format
          enum:
            - mp4
            - zip
            - jpeg
            - prores
            - png
        resolution:
          type: string
          description: Friendly name for resolution
          enum:
            - 6k-pro
            - 4K-pro
            - 1080p-pro
            - 4K
            - 1080p
            - 720p
            - dw-pro
            - tw-pro
        url:
          type: string
          example: https://cloudfront.net/productid/downloadid.mp4
          description: Base URL for download without signing parameters
        size:
          type: integer
          format: int64
          description: File size in bytes
          example: 24523
    UpdateBundle:
      type: object
      required:
        - id
        - thumbnail
        - preview_hover
        - preview_video
        - downloads
      properties:
        id:
          type: integer
          format: int64
          example: 5
          description: Unique ID of bundle generated by Wordpress
        thumbnail:
          type: string
          description: Static image used in content lists on the website
          example: https://cloudfront.net/bundleId/thumbnail.jpg
        preview_hover:
          type: string
          description: Played when user hovers over thumbnail
          example: https://cloudfront.net/bundleId/preview_hover.mp4
        preview_video:
          type: string
          description: Featured preview on bundle product page
          example: https://cloudfront.net/bundleId/preview_video.mp4
        downloads:
          description: List of bundle downloads
          type: array
          items:
            $ref: "#/components/schemas/Download"
    UpdateProduct:
      type: object
      required:
        - id
        - thumbnail
        - preview_hover
        - downloads
      properties:
        id:
          type: integer
          format: int64
          example: 5
          description: Unique ID of product generated by Wordpress
        duration:
          type: integer
          format: int64
          description: Duration in seconds if the product is a video
          example: 125
        thumbnail:
          type: string
          description: Static image used in content lists on the website
          example: https://cloudfront.net/bundleId/thumbnail.jpg
        preview_hover:
          type: string
          description: Played when user hovers over thumbnail
          example: https://cloudfront.net/bundleId/preview_hover.mp4
        preview_video_full:
          type: string
          description: Full streaming video preview when a specific video is clicked on a product page
          example: https://vimeo.com/someVimeoId
        preview_image_full:
          type: string
          description: Full quality image preview
          example: https://cloudfront.net/bundleId/preview_image_full.jpg
        downloads:
          description: List of downloads for the product
          type: array
          items:
            $ref: "#/components/schemas/Download"
    CreateProduct:
      type: object
      required:
        - bundle_id
        - name
        - type
        - description
        - thumbnail
        - preview_hover
        - downloads
      properties:
        bundle_id:
          type: integer
          format: int64
          example: 1
          description: Parent bundle ID for product
        name:
          type: string
          example: Prism Glow 01
          description: Name of product
        type:
          type: string
          description: Content type
          enum:
            - motion-background
            - still
            - countdown
            - motion-title
            - title-slide
            - title-overlay
            - propresenter-7
        description:
          type: string
          example: Colorful bokeh drifting and evolve across the screen creating beautiful lens effects.
          description: Description of product
        duration:
          type: integer
          format: int64
          description: Duration in seconds if the product is a video
          example: 125
        thumbnail:
          type: string
          description: Static image used in content lists on the website
          example: https://cloudfront.net/bundleId/thumbnail.jpg
        preview_hover:
          type: string
          description: Played when user hovers over thumbnail
          example: https://cloudfront.net/bundleId/preview_hover.mp4
        preview_video_full:
          type: string
          description: Full streaming video preview when a specific video is clicked on a product page
          example: https://vimeo.com/someVimeoId
        preview_image_full:
          type: string
          description: Full quality image preview
          example: https://cloudfront.net/bundleId/preview_image_full.jpg
        downloads:
          description: List of downloads for the product
          type: array
          items:
            $ref: "#/components/schemas/NewDownload"
    PackProcessorOutput:
      type: object
      required:
        - id
        - downloads
      properties:
        id:
          type: integer
          format: int64
          description: Bundle ID from Wordpress. This should always be present.
          example: 123
        thumbnail:
          type: string
          description: S3 Key of the uploaded thumbnail image for the bundle. Only required when creating a bundle.
          example: 123/public/thumbnail.jpg
        previewHover:
          type: string
          description: S3 Key of the uploaded hover preview image for the bundle. This is used in thumbnail listings. Only required when creating a bundle.
          example: 123/public/preview_hover.jpg
        previewVideo:
          type: string
          description: S3 Key of the uploaded HQ video preview for the bundle. This is the featured looping video on the bundle page. Only required when creating a bundle.
          example: 123/public/preview_video.mp4
        downloads:
          type: array
          description: List of downloads for the bundle
          items:
            $ref: "#/components/schemas/PackProcessorBundleDownload"
        products:
          type: array
          description: List of products for the bundle
          items:
            $ref: "#/components/schemas/PackProcessorProduct"
    PackProcessorProduct:
      type: object
      required:
        - downloads
      properties:
        name:
          type: string
          description: Product name. Only required when creating a product.
          example: Prism Glow Motion Background 01
        description:
          type: string
          description: Product description. Only required when creating a product.
          example: Product specific description
        id:
          type: integer
          format: int64
          description: Product ID from Wordpress. Only required when updating an existing product
          example: 456
        type:
          type: string
          description: Media type
          enum:
            - motion-background
            - still
            - countdown
            - motion-title
            - title-slide
            - title-overlay
            - propresenter-7
        duration:
          type: int
          format: int64
          description: Duration in seconds if the product is a video
          example: 30000
        thumbnail:
          type: string
          description: S3 Key of the uploaded thumbnail image for the product. Only required when creating a product.
          example: 123/motion-background/public/01_thumbnail.jpg
        previewHover:
          type: string
          description: S3 Key of the uploaded hover preview image for the product. This is used in thumbnail listings. Only required when creating a product.
          example: 123/motion-background/public/01_preview_hover.jpg
        previewVideoFull:
          type: string
          description: Vimeo URL for the full streaming video preview. Only required when creating a product.
          example: https://vimeo.com/456
        previewImageFull:
          type: string
          description: S3 Key of full quality image for media types that are not video
          example: 123/still/public/01_preview_image_full.jpg
        downloads:
          type: array
          description: List of downloads for the product
          items:
            $ref: "#/components/schemas/PackProcessorProductDownload"
    PackProcessorBundleDownload:
      type: object
      required:
        - filename
        - type
        - format
        - key
      properties:
        id:
          type: string
          format: uuid
          description: Unique download ID generated in AWS. This indicates an update/edit when provided.
        filename:
          type: string
          example: BundleDownloadFilename.mp4
          description: Friendly name of file including extension
        type:
          type: string
          description: Media type
          enum:
            - motion-background
            - still
            - countdown
            - motion-title
            - title-slide
            - title-overlay
            - propresenter-7
        format:
          type: string
          description: File format
          enum:
            - mp4
            - zip
            - jpeg
            - prores
            - png
        resolution:
          type: string
          description: Friendly name for resolution
          enum:
            - 6k-pro
            - 4K-pro
            - 1080p-pro
            - 4K
            - 1080p
            - 720p
            - dw-pro
            - tw-pro
        key:
          type: string
          example: 123/motion-background/private/6k-pro/
          description: S3 Key of the uploaded download file. For bundle downloads, this should be a path ending in /. For products, it should be the full object key.
    PackProcessorProductDownload:
      type: object
      required:
        - filename
        - type
        - format
        - key
        - size
      properties:
        id:
          type: string
          format: uuid
          description: Unique download ID generated in AWS. This indicates an update/edit when provided.
          example: db3e63a3-3fdc-4a21-9375-089b6e31081e
        filename:
          type: string
          example: ProductDownloadFilename.mp4
          description: Friendly name of file including extension
        type:
          type: string
          description: Media type
          enum:
            - motion-background
            - still
            - countdown
            - motion-title
            - title-slide
            - title-overlay
            - propresenter-7
        format:
          type: string
          description: File format
          enum:
            - mp4
            - zip
            - jpeg
            - prores
            - png
        resolution:
          type: string
          description: Friendly name for resolution
          enum:
            - 6k-pro
            - 4K-pro
            - 1080p-pro
            - 4K
            - 1080p
            - 720p
            - dw-pro
            - tw-pro
        key:
          type: string
          example: 123/motion-background/private/6k-pro/01.mp4
          description: S3 Key of the uploaded download file. For bundle downloads, this should be a path ending in /. For products, it should be the full object key.
        size:
          type: integer
          format: int64
          description: File size in bytes
          example: 24523
